
name: Deploy static/react projects to GH Pages

on:
  push:
    branches: ["main"]

  # run workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build React Apps
    - name: Build React Apps
      run: |
        mkdir -p final_build
        echo "Processing React apps in react-sites/"
        for dir in react-sites/*/; do
          if [ -f "$dir/package.json" ]; then
            echo "Building React app in $dir"
            cd "$dir"
            npm i
            npm run build
            mv build ../../final_build/$(basename "$dir") # Move the built app
            cd -
          else
            echo "No package.json found in $dir, skipping..."
          fi
        done

    # Step 3: Copy Static Sites
    - name: Copy Static Sites
      run: |
        echo "Processing static sites in static-sites/"
        for dir in static-sites/*/; do
          if [ -f "$dir/index.html" ]; then
            echo "Copying static site from $dir"
            mkdir -p final_build/$(basename "$dir")
            cp -r $dir/* final_build/$(basename "$dir") # Copy static site files
          else
            echo "No index.html found in $dir, skipping..."
          fi
        done

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: final_build