
name: Deploy static/react projects to GH Pages

on:
  push:
    branches: ["main"]

  # run workflow manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build React Apps
      working-directory: react-sites
      run: |
        npm i
        npm run build

    - name: Prepare Deployment Directory
      run: |
        mkdir final_build
        echo "Copying static site"
        cp -r static-sites/* final_build/
        echo "Copying React app"
        cp -r react-sites/build/* final_build/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: final_build